### PR TITLE
master password and new crypto

### PR DESCRIPTION
**Pull request by styler2go**
I added a better crypto class and also added a master password which needs to be typed in each time. This will increase security a little bit.

### CODE REVIEW

**Comment by Rottweiler** [comment]
Master password should be optional. I can imagine not everyone wants to enter it every single time.

**Comment by W3D3** [comment]
I like the idea, but I also think that the password should be optional. This update would also break compatibility with account-files created by previous versions of the program, right?

**Comment by styler2go** [comment]
That's true. It would make current account-files useless.

I can't think of a good Idea to make it optional. I closed the merge requests.

**Comment by W3D3** [comment]
@styler2go I think the best method would be to create a settings panel where the user can chose a encryption method.
Maybe you could reopen a merge request without overwriting the original Crypto class.

**Comment by styler2go** [comment]
Maybe a "first-time configuration" on first startup?
The Crypto class can be used with a master password and without so i think we can use that on both, password encrypted and default encrypted files.

**Comment by W3D3** [comment]
@styler2go 
Yeah sounds like a good idea. Would it be a possibility that the encryption was using a hardware key to bind the program to this machine without having the user to enter a password every time?
So that there are the 3 options "simple encryption", "master password", "bind to hardware"?

I just like to have it in place because i don't like to break compatibility, so that after updating the old class can decrypt and give it to the new one to encrypt it again.

**Comment by styler2go** [comment]
Yes, that'd be a nice option.
I think i could also do a "merge simple encryption to bind to hardware or master password" for people who want to use a password afterwards.

**Pull request closed without merging**
